FROM nginx:alpine
LABEL org.opencontainers.image.authors="fromero@fp.lasalle.es, rgonzalez@fp.lasalle.es"
LABEL version="0.1.0"

#TODO: [...] Añadir configuración necesaria para generar la imagen del frontend
